version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - internal

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - internal

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
    driver: bridge
